/*
 * CS210 Chapter 3 Exercise 17 
 * Wilbert Lim Sible
 * wilbert.sible@bellevuecollege.edu
 * 2018/01/16 - winter quarter
 *
 * This program uses the parameters to print a word and add spaces after it. The parameters defined are the word and the
 * total characters in the line including the word. If the characters in the word are less than the character parameter,
 * spaces will be added until the total characters in the line correspond to the parameter given. Otherwise, if the word is
 * longer than the number of characters, no spaces will be printed. 
 */

public class PadString {

	public static void main(String[] args) {
		System.out.println(padString("hello", 8)); // Used to test the parameters given.
		System.out.println(padString("congratulations", 10));

	}
	public static String padString (String word, int totalchar) {
		String space = ""; // Declaration and assignment of variable
		int s = totalchar - word.length(); // Number of spaces that will be added
		for (int i = 1; i <=s; i++) { // For loop that prints the spaces  into the variable
			space += " ";
		}
		return word + space; // Concatenating the word and the spaces generated by the for loop
	}
}
